name: Build & Release PowerSchool Plugin

on:
  release:
    types: [created]

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse numeric version
        id: version
        run: |
          RAW_VERSION="${GITHUB_REF##*/}"
          CLEAN_VERSION="${RAW_VERSION#v}"
          NUMERIC_VERSION=$(echo "$CLEAN_VERSION" | sed 's/[^0-9.].*//')
          echo "NUMERIC_VERSION=$NUMERIC_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build plugin folder
        run: |
          mkdir -p dist/${PLUGIN_NAME}/web_root
          cp -R WEB_ROOT/* dist/${PLUGIN_NAME}/web_root

          mkdir -p dist/${PLUGIN_NAME}/pagecataloging
          sed "s/__VERSION__/${{ steps.version.outputs.NUMERIC_VERSION }}/g" pagecataloging/pages.json > dist/${PLUGIN_NAME}/pagecataloging/pages.json

          sed "s/__VERSION__/${{ steps.version.outputs.NUMERIC_VERSION }}/g" plugin.xml > dist/${PLUGIN_NAME}/plugin.xml

      - name: Zip plugin contents
        run: |
          cd dist/${PLUGIN_NAME}
          zip -r ../${PLUGIN_NAME}-${{ github.ref_name }}.zip ./*
          cd ../..

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
          token: ${{ secrets.GH_PAT }}
